"""Generate ``THIRD_PARTY_LICENSES.txt`` for the plain portable viewer.

This module has two jobs:

1. **The viewer's own notice** (:func:`generate` / the CLI): the notice file
   shipped with the plain distribution (``dist/snappix-viewer/``) and
   committed at the repo root.  Its package set is the *explicit dependency
   closure* of pyproject's ``[project.dependencies]`` (minus
   :data:`VIEWER_EXCLUDED` — numpy is excluded from the frozen viewer by
   ``snappix_viewer.spec``), so plugin-only dependencies (torch/CUDA, a
   plugin's vendored closure, …) never appear.  The viewer-only public
   snapshot (``tools/public_export.py`` — no ``plugins/``) is therefore
   fully self-describing.
2. **A reusable harvesting library** for the plugins' own notices: each
   separately-distributed plugin pack carries its own
   ``THIRD_PARTY_LICENSES.txt``, generated at build time by the plugin's
   ``build_hook.py`` (``plugins/<id>/build_hook.py``) from the helpers
   exported here (:func:`dependency_closure`, :func:`package_sections`,
   :func:`full_texts`, :func:`banner`, …).

The harvesting approach (shared by every notice):

* Reproduce the license text each bundled Python package ships in its
  ``*.dist-info`` metadata (the authoritative per-package copyright line +
  permission text — reproducing it verbatim is exactly what MIT / BSD /
  Apache / ISC / MPL / etc. require).
* Prepend hand-authored sections that ``dist-info`` cannot provide (bundled
  native components, copyleft-compliance statements).  Packages whose wheel
  ships **no** license file in dist-info (loguru) get the canonical upstream
  text from :data:`FALLBACK_LICENSE_TEXTS`.
* Append the canonical GNU **LGPL-3.0** and **GPL-3.0** full texts (read
  from ``licenses/`` — PySide6's wheel ships only its *commercial* license
  reference, not the open-source text, so we keep the canonical copies in
  the repo).

Usage::

    uv run python tools/gen_third_party_licenses.py          # refresh the
                                                             # committed file
    uv run python tools/gen_third_party_licenses.py <path>   # write elsewhere

``build_portable.py`` also imports :func:`generate` so the shipped ``dist/``
always carries a notice matching exactly the packages that were frozen in.
"""

from __future__ import annotations

import importlib.metadata as im
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LICENSES_DIR = ROOT / "licenses"
DEFAULT_OUT = ROOT / "THIRD_PARTY_LICENSES.txt"

# ---------------------------------------------------------------------------
# The viewer's package set: the transitive closure of pyproject's main
# dependencies.  Explicit-closure (rather than "everything installed in the
# venv") keeps plugin-only dependencies out even when the build venv has the
# ``tagger`` extra or plugin-layered dependencies co-installed.
#
# numpy is excluded: the plain frozen viewer EXCLUDES numpy
# (snappix_viewer.spec) — it ships only inside the paid AI plugin's vendor/
# (whose own notice, generated by the plugin's build hook, covers it).
VIEWER_EXCLUDED = {"numpy"}

# Distributions handled entirely by the hand-authored compliance section
# (their dist-info ships only a *commercial* license reference, which would be
# misleading to reproduce — the app uses them under the LGPL v3 covered in
# section 2 + the full text in section 4).
COPYLEFT_HANDLED = {
    "pyside6",
    "pyside6_addons",
    "pyside6-addons",
    "pyside6_essentials",
    "pyside6-essentials",
    "shiboken6",
}

_LICENSE_FILE_TOKENS = ("license", "licence", "copying", "notice", "authors")
# Skip commercial / non-applicable license references when harvesting.
_LICENSE_FILE_SKIP = ("qt-commercial",)

#: The bare MIT permission text (without a copyright line) — reused by
#: hand-authored sections that attribute MIT-licensed native binaries
#: (e.g. a plugin's bundled JavaScript runtime entries).
MIT_PERMISSION_TEXT = """\
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE."""

# Canonical license texts for packages whose wheel ships NO license file in
# its dist-info metadata. A missing file in the wheel does not lift the
# obligation — MIT & friends require reproducing the copyright + permission
# notice when redistributing — so the upstream text is hand-carried here
# (verified verbatim against the project repository), keyed by normalized
# dist name.
FALLBACK_LICENSE_TEXTS = {
    # https://github.com/Delgan/loguru/blob/master/LICENSE
    "loguru": "MIT License\n\nCopyright (c) 2017\n\n" + MIT_PERMISSION_TEXT,
    # The two win32-only transitive deps of loguru (sys_platform == 'win32').
    # The closure targets the SHIPPED platform (Windows), so they are always
    # part of the viewer notice — but a Linux dev venv does not install them
    # (uv honours the marker), so their texts are hand-carried verbatim from
    # the wheels for the not-installed generation path (_AbsentDistribution).
    # https://github.com/tartley/colorama/blob/master/LICENSE.txt
    "colorama": """\
Copyright (c) 2010 Jonathan Hartley
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holders, nor those of its contributors
  may be used to endorse or promote products derived from this software without
  specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.""",
    # https://github.com/Delgan/win32-setctime/blob/master/LICENSE
    "win32-setctime": (
        "MIT License\n\nCopyright (c) 2019 Delgan\n\n" + MIT_PERMISSION_TEXT
    ),
}

#: SPDX identifiers for the hand-carried fallback entries above, used when
#: the wheel itself is absent from the generating venv and no metadata can be
#: read (see :class:`_AbsentDistribution`).
_FALLBACK_SPDX = {
    "loguru": "MIT",
    "colorama": "BSD-3-Clause",
    "win32-setctime": "MIT",
}


def norm(name: str) -> str:
    """PEP 503-ish normalisation (lowercase, ``_`` → ``-``)."""
    return name.lower().replace("_", "-")


def distinfo_dir(dist: im.Distribution) -> Path | None:
    """The distribution's ``*.dist-info`` directory, when it has one on disk.

    Public because the plugins' build hooks need the same anchor (the
    per-package license text and the installed payload both live next to it).
    """
    path = getattr(dist, "_path", None)
    if path is not None:
        return Path(path)
    return None


def dist_top_level_import_names(dist: im.Distribution) -> set[str]:
    """Top-level import names a distribution installs (packages + modules).

    Prefers the authoritative ``top_level.txt``; otherwise derives them from
    the installed file list, so ``Pillow`` → ``PIL`` and ``markdown-it-py`` →
    ``markdown_it``.  Extension modules carrying an ABI tag
    (``_cffi_backend.cp312-win_amd64.pyd``) collapse to their import name, and
    bogus ``..`` script paths / ``*.dist-info`` / ``*.data`` entries drop out.

    Two build-time consumers need exactly this mapping and used to carry a
    copy each: the host's unlicensed-package check (frozen top-level names →
    the notice's dependency closure) and plugin vendoring (which
    payload directories/files to copy next to the pack).
    """
    info = distinfo_dir(dist)
    if info is not None:
        tl = info / "top_level.txt"
        if tl.is_file():
            names = {
                ln.strip().split("/")[0]
                for ln in tl.read_text(encoding="utf-8").splitlines()
                if ln.strip() and ln.strip() != ".."
            }
            if names:
                return names
    names = set()
    for f in dist.files or []:
        parts = f.parts
        if not parts or parts[0] == "..":
            continue
        first = parts[0]
        if first.endswith((".dist-info", ".data")):
            continue
        if len(parts) == 1:
            if first.endswith((".py", ".pyd", ".so", ".pyi")):
                names.add(first.split(".")[0])
        else:
            names.add(first)
    names.discard("")
    return names


def license_files(dist: im.Distribution) -> list[Path]:
    """Return the on-disk license/notice files a distribution ships."""
    info = distinfo_dir(dist)
    if info is None or not info.is_dir():
        return []
    out: list[Path] = []
    for p in sorted(info.rglob("*")):
        if not p.is_file():
            continue
        low = p.name.lower()
        if not any(tok in low for tok in _LICENSE_FILE_TOKENS):
            continue
        if any(skip in low for skip in _LICENSE_FILE_SKIP):
            continue
        # RECORD / METADATA / WHEEL etc. never match the tokens above, so this
        # is just the license/notice/authors set.
        out.append(p)
    return out


def spdx(dist: im.Distribution) -> str:
    md = dist.metadata
    expr = md.get("License-Expression")
    if expr:
        return expr.strip()
    classifiers = [
        c.split("::")[-1].strip()
        for c in md.get_all("Classifier", []) or []
        if c.startswith("License ::")
    ]
    if classifiers:
        return " / ".join(dict.fromkeys(classifiers))
    lic = (md.get("License") or "").strip()
    if lic and len(lic) <= 60 and "\n" not in lic:
        return lic
    return "(see license text below)"


def embedded_license_banners(
    dist: im.Distribution, embedded_files: dict[str, list[str]]
) -> list[str]:
    """Return license banner comments embedded in a package's data files.

    Some packages vendor third-party code as *data files* (not as separate
    installed distributions) whose license text lives in a leading
    ``/* ... */`` banner (e.g. minified JS bundles), so importlib.metadata
    never sees them.  *embedded_files* maps normalized dist name → data files
    to scan; the caller (a plugin's notice generator) supplies the map for
    the packages it actually vendors.
    """
    import re

    key = norm(dist.metadata.get("Name", ""))
    rels = embedded_files.get(key)
    if not rels:
        return []
    banners: list[str] = []
    for rel in rels:
        try:
            text = Path(dist.locate_file(rel)).read_text(
                encoding="utf-8", errors="replace"
            )
        except OSError:
            continue
        for m in re.finditer(r"/\*(.*?)\*/", text, re.S):
            block = m.group(1)
            if "Bundled Dependencies" in block or (
                "License" in block and "Copyright" in block
            ):
                # Strip a leading decorative "!" and per-line " * " gutters.
                lines = [
                    ln[3:] if ln.startswith(" * ") else ln.lstrip(" *")
                    for ln in block.splitlines()
                ]
                cleaned = "\n".join(lines).strip("!\n ")
                if cleaned not in banners:
                    banners.append(cleaned)
    return banners


def _windows_target_environment() -> dict:
    """The marker environment of the SHIPPED platform (Windows portable exe).

    Dependency markers must be evaluated against the platform the product
    ships on, not the machine the notice happens to be generated on —
    otherwise the package set (and therefore the committed
    THIRD_PARTY_LICENSES.txt) silently diverges between a Linux dev box and
    the Windows CI/build runner (e.g. loguru's ``colorama`` /
    ``win32-setctime``, both ``sys_platform == 'win32'``-gated).
    """
    from packaging.markers import default_environment

    env = dict(default_environment())
    env.update(
        {
            "sys_platform": "win32",
            "platform_system": "Windows",
            "os_name": "nt",
            "platform_machine": "AMD64",
        }
    )
    return env


def dependency_closure(
    roots: list[tuple[str, set[str]]], env: dict | None = None
) -> set[str]:
    """Transitive runtime dependency closure of *roots* (normalized names).

    *roots* is a list of ``(dist_name, extras_to_follow)``.  Requirements are
    parsed with :mod:`packaging` and their markers evaluated against the
    SHIPPED platform (:func:`_windows_target_environment` — deterministic
    across dev/CI operating systems) unless *env* overrides it; an
    ``extra == '…'`` requirement is followed only when that extra was
    requested for the dist declaring it (so httpx[http2] pulls h2 but not
    httpx's cli/brotli extras).  Missing dists are silently skipped — the
    caller decides whether absence is an error.
    """
    from collections import deque

    from packaging.requirements import Requirement

    if env is None:
        env = _windows_target_environment()

    resolved: dict[str, frozenset[str]] = {}
    queue: deque[tuple[str, frozenset[str]]] = deque(
        (norm(name), frozenset(extras)) for name, extras in roots
    )
    result: set[str] = set()
    while queue:
        key, extras = queue.popleft()
        prev = resolved.get(key)
        if prev is not None and extras <= prev:
            continue
        merged = (prev or frozenset()) | extras
        resolved[key] = merged
        result.add(key)
        try:
            dist = im.distribution(key)
        except im.PackageNotFoundError:
            continue
        for rstr in dist.requires or []:
            try:
                req = Requirement(rstr)
            except Exception:
                continue
            marker = req.marker
            include = marker is None or marker.evaluate({**env, "extra": ""})
            if not include:
                include = any(
                    marker.evaluate({**env, "extra": e}) for e in merged
                )
            if include:
                # Carry the requirement's bracket extras (``foo[bar]``) into the
                # closure so a transitive dist's *conditional* dependencies are
                # followed too — dropping them here would silently omit the
                # ``bar`` extra's deps from both the vendored closure and the
                # license notice.
                queue.append((norm(req.name), frozenset(req.extras)))
    return result


def pyproject_dependency_roots(
    pyproject: Path, extra: str | None = None
) -> list[tuple[str, set[str]]]:
    """Direct dependencies declared in *pyproject* as closure roots.

    ``[project.dependencies]``, or the ``extra`` optional-dependencies group
    when given.  Extras requested in the requirement string (``httpx[http2]``
    style) are carried into the closure; version specifiers are ignored (the
    closure is computed against the installed venv, whose versions uv.lock
    pins).
    """
    import re

    project = tomllib.loads(pyproject.read_text(encoding="utf-8"))["project"]
    reqs = (
        project.get("optional-dependencies", {}).get(extra, [])
        if extra
        else project.get("dependencies", [])
    )
    roots: list[tuple[str, set[str]]] = []
    for req in reqs:
        m = re.match(r"\s*([A-Za-z0-9._-]+)\s*(?:\[([^\]]*)\])?", req)
        if not m:
            continue
        name = m.group(1)
        extras = {
            e.strip() for e in (m.group(2) or "").split(",") if e.strip()
        }
        roots.append((name, extras))
    return roots


def pyproject_main_dependency_roots() -> list[tuple[str, set[str]]]:
    """The viewer's direct dependencies from pyproject ``[project.dependencies]``."""
    return pyproject_dependency_roots(ROOT / "pyproject.toml")


def distributions_by_names(names: list[str]) -> list[im.Distribution]:
    """Resolve normalized dist names to Distribution objects (sorted, deduped).

    Names not installed in the current environment are skipped.
    """
    seen: dict[str, im.Distribution] = {}
    for name in names:
        key = norm(name)
        if key in seen:
            continue
        try:
            seen[key] = im.distribution(key)
        except im.PackageNotFoundError:
            continue
    return [seen[k] for k in sorted(seen)]


def viewer_distribution_names() -> list[str]:
    """The plain viewer's bundled package set (normalized names, sorted)."""
    closure = dependency_closure(pyproject_main_dependency_roots())
    return sorted(closure - {norm(n) for n in VIEWER_EXCLUDED})


class _AbsentDistribution:
    """Stand-in for a closure member whose wheel is absent from this venv.

    The closure targets the shipped platform (Windows), so a Linux dev venv
    legitimately lacks the ``sys_platform == 'win32'`` members (uv honours
    the marker).  Their notice entry still must appear — the version comes
    from the committed uv.lock (the authoritative pin the Windows build
    installs) and the license text from :data:`FALLBACK_LICENSE_TEXTS`.
    Duck-types the small ``importlib.metadata.Distribution`` surface the
    section builder reads (``metadata.get`` / no ``_path`` → no on-disk
    license files → fallback text).
    """

    def __init__(self, name: str, version: str) -> None:
        self._md = {
            "Name": name,
            "Version": version,
            "License-Expression": _FALLBACK_SPDX.get(norm(name), ""),
        }

    @property
    def metadata(self):
        return self

    def get(self, key: str, default=None):
        return self._md.get(key, default)

    def get_all(self, key: str, default=None):
        return default


def _uv_lock_version(name: str) -> str:
    """The version uv.lock pins for *name* ('' when absent from the lock)."""
    lock_path = ROOT / "uv.lock"
    if not lock_path.is_file():
        return ""
    data = tomllib.loads(lock_path.read_text(encoding="utf-8"))
    for pkg in data.get("package", []):
        if norm(pkg.get("name", "")) == norm(name):
            return pkg.get("version", "")
    return ""


# ---------------------------------------------------------------------------
# Hand-authored sections.

_BANNER = "=" * 78


def banner(title: str) -> str:
    return f"{_BANNER}\n{title}\n{_BANNER}\n"


_HEADER = banner(
    "Snappix Viewer — Third-Party Software Notices and Licenses"
) + """
このファイルは Snappix Viewer 本体（dist/snappix-viewer/）の配布物に同梱される
第三者ソフトウェアの著作権・ライセンス表記です。別売・別配布のプラグイン
（AI 検索プラグインなど）は、それぞれのプラグインフォルダに自前の
THIRD_PARTY_LICENSES.txt を同梱します — 本ファイルはビューア本体が同梱する
コンポーネントのみを記載します。以下のすべてのコンポーネントは再配布が許諾
されており、配布を禁止するものは含まれていません。（This file lists the
copyright and license notices for the third-party software bundled with the
Snappix Viewer application itself (dist/snappix-viewer/). Separately
distributed plugins carry their own THIRD_PARTY_LICENSES.txt inside their
plugin folder; this document covers only the components the viewer app
bundles. Every component below is redistributable.)

Contents:
  1. Bundled native components (FFmpeg DLLs via Qt Multimedia; the CPython
     runtime)
  2. Copyleft compliance notices (Qt / PySide6 — LGPL v3)
  3. Bundled Python packages — per-package license texts
  4. Full license texts: GNU LGPL v3 and GNU GPL v3
"""


def cpython_license_text() -> str:
    """The build interpreter's own LICENSE.txt, reproduced verbatim.

    ``sys.base_prefix`` is the real CPython installation even when running
    inside a venv, i.e. exactly the runtime PyInstaller freezes into the
    dist. The PSF license requires retaining the license text, so reproduce
    it rather than merely linking to python.org.
    """
    for name in ("LICENSE.txt", "LICENSE"):
        path = Path(sys.base_prefix) / name
        if path.is_file():
            return path.read_text(encoding="utf-8", errors="replace").rstrip("\n")
    return (
        "(The build interpreter did not ship a LICENSE file on disk; the\n"
        "PSF License Agreement is available at https://docs.python.org/3/license.html)"
    )


def indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + ln if ln else ln for ln in text.splitlines())


def cpython_runtime_entry() -> str:
    """The CPython runtime attribution block (shared by every frozen app)."""
    return f"""CPython runtime  (bundled by PyInstaller as python3*.dll + the standard
    library under _internal/)
    License:   Python Software Foundation License Agreement (PSF), reproduced
               below as shipped by the interpreter this distribution was
               frozen from.
    Copyright: © the Python Software Foundation.
    Source:    https://www.python.org/

{indent(cpython_license_text(), 4)}

Note on the freezer: the executables are produced with PyInstaller, whose
bootloader is distributed under the GPL v2.0 *with an explicit exception* that
permits shipping the frozen application under any license of your choosing.
PyInstaller itself is a build tool and is not otherwise part of the shipped
application."""


def _native_binaries_section() -> str:
    return banner("1. Bundled native components") + f"""
FFmpeg libraries bundled with Qt Multimedia  (_internal/PySide6/avcodec-*.dll,
    avformat-*.dll, avutil-*.dll, swresample-*.dll, swscale-*.dll)
    The LGPL FFmpeg build The Qt Company ships inside the PySide6 wheels as
    the media backend of Qt Multimedia (used by the viewer's audio / video
    preview).
    License:   GNU LGPL (v2.1 or later), as distributed by The Qt Company.
    Copyright: © the FFmpeg developers.
    Source:    https://ffmpeg.org/
               (Qt's FFmpeg integration: https://code.qt.io/cgit/qt/qtmultimedia.git/)
    LGPL relinking: these DLLs are dynamically loaded and may be replaced
               with your own compatible FFmpeg builds.

{cpython_runtime_entry()}
"""


_COMPLIANCE = banner("2. Copyleft compliance notices") + """
Qt / PySide6 / shiboken6  (LGPL v3)
    This application uses the Qt framework through the PySide6 Python bindings
    (packages PySide6, PySide6_Essentials, PySide6_Addons and shiboken6). Qt
    and PySide6 are used here under the terms of the GNU Lesser General Public
    License, version 3 (LGPL v3). The full LGPL v3 and GPL v3 texts (LGPL v3 is
    a set of additional permissions on top of GPL v3) are in section 4.

    - The Qt libraries are shipped as separate, dynamically-loaded DLLs under
      ``_internal/PySide6/`` and ``_internal/shiboken6/``. As permitted by
      LGPL v3 §4, you may replace them with your own compatible builds of Qt /
      PySide6.
    - Only LGPL-licensed Qt modules are used (Qt Core, Gui, Widgets, Svg,
      Network, Multimedia, MultimediaWidgets, Pdf and PdfWidgets). The Qt
      modules that are GPL-only in open-source Qt (Qt Charts, Qt Data
      Visualization, Qt Virtual Keyboard, Qt Quick 3D, Qt Graphs, Qt Quick
      Timeline, among others — see https://doc.qt.io/qt-6/licensing.html)
      are NOT used or shipped. Qt WebEngine (LGPL-licensed, but not needed
      by this application) is likewise NOT used or shipped.
    - Qt Pdf incorporates a snapshot of PDFium (BSD-3-Clause) together with
      the third-party components PDFium itself bundles; see
      https://pdfium.googlesource.com/pdfium/ .
    - Qt Multimedia dynamically loads the FFmpeg LGPL libraries shipped in
      the PySide6 wheel — see "FFmpeg libraries bundled with Qt Multimedia"
      in section 1.
    - Copyright: © The Qt Company Ltd and other contributors.
    - Source (corresponding library source):
        Qt:      https://download.qt.io/official_releases/qt/
        PySide6: https://code.qt.io/cgit/pyside/pyside-setup.git/  (also
                 available as the sdist on https://pypi.org/project/PySide6/)
"""


def package_sections(
    dists: list[im.Distribution],
    intro: str,
    *,
    copyleft_handled: set[str] | None = None,
    embedded_files: dict[str, list[str]] | None = None,
) -> str:
    """Section 3 — per-package license texts for *dists*.

    *copyleft_handled* names dists whose notice is the hand-authored
    compliance section (Qt/PySide6); *embedded_files* optionally maps dist
    names to data files whose embedded license banners should be harvested
    (see :func:`embedded_license_banners`).
    """
    handled = copyleft_handled if copyleft_handled is not None else COPYLEFT_HANDLED
    parts: list[str] = [banner("3. Bundled Python packages")]
    parts.append(intro)
    for dist in dists:
        name = dist.metadata.get("Name")
        version = dist.metadata.get("Version", "")
        key = norm(name)
        head = f"\n{'-' * 78}\n{name}  {version}\nSPDX/License: {spdx(dist)}\n{'-' * 78}\n"
        parts.append(head)
        if key in handled:
            parts.append(
                "Used under the GNU LGPL v3 — see section 2 (Copyleft compliance "
                "notices)\nand section 4 (full LGPL v3 / GPL v3 texts).\n"
            )
            continue
        files = license_files(dist)
        if not files and key in FALLBACK_LICENSE_TEXTS:
            parts.append(
                "[license text reproduced from the upstream project — this "
                "package's wheel\nships no license file in its metadata]\n"
                f"{FALLBACK_LICENSE_TEXTS[key]}\n"
            )
        elif not files:
            parts.append(
                "(No license file shipped in this package's metadata; the "
                "SPDX identifier above\nrecords its license.)\n"
            )
        for f in files:
            text = f.read_text(encoding="utf-8", errors="replace").rstrip("\n")
            parts.append(f"[{f.name}]\n{text}\n")
        if embedded_files:
            for banner_text in embedded_license_banners(dist, embedded_files):
                parts.append(f"[bundled dependencies]\n{banner_text}\n")
    return "\n".join(parts)


def full_texts() -> str:
    out = [banner("4. Full license texts")]
    for label, fname in (
        ("GNU LESSER GENERAL PUBLIC LICENSE, Version 3", "LGPL-3.0.txt"),
        ("GNU GENERAL PUBLIC LICENSE, Version 3", "GPL-3.0.txt"),
    ):
        path = LICENSES_DIR / fname
        if not path.is_file():
            raise SystemExit(
                f"[gen-licenses] missing canonical text: {path}. "
                "Restore it (e.g. curl https://www.gnu.org/licenses/"
                f"{fname.lower()})."
            )
        text = path.read_text(encoding="utf-8").rstrip("\n")
        out.append(f"\n{'-' * 78}\n{label}\n{'-' * 78}\n{text}\n")
    return "\n".join(out)


_PACKAGES_INTRO = (
    "Each package below is reproduced with the exact license / notice text\n"
    "it ships in its distribution metadata. Qt/PySide6 components are\n"
    "routed to the LGPL compliance notice in section 2. For packages whose\n"
    "wheel ships no license file, the canonical upstream text is\n"
    "reproduced instead.  The set is the dependency closure of the viewer\n"
    "app (pyproject [project.dependencies]); numpy is absent by design (the\n"
    "frozen viewer excludes it — it ships only inside the AI plugin pack,\n"
    "whose own notice covers it).\n"
)


def build_document() -> str:
    names = viewer_distribution_names()
    dists = list(distributions_by_names(names))
    installed = {norm(d.metadata.get("Name", "")) for d in dists}
    missing = sorted(set(names) - installed)
    # Under-inclusion is the real compliance hazard: a closure member whose
    # wheel is absent from this venv must not silently drop out of the
    # shipped notice.  The known platform-gated members (win32-only, absent
    # from a Linux dev venv) get a hand-carried entry; anything else missing
    # means the venv is stale — fail loudly.
    unaccounted = [n for n in missing if n not in FALLBACK_LICENSE_TEXTS]
    if unaccounted:
        raise SystemExit(
            "[gen-licenses] closure members not installed in this venv "
            "(their license texts cannot be harvested): "
            + ", ".join(unaccounted)
            + "\n    Run `uv sync --extra dev` and retry."
        )
    dists += [_AbsentDistribution(n, _uv_lock_version(n)) for n in missing]
    dists.sort(key=lambda d: norm(d.metadata.get("Name", "")))
    return "\n".join(
        [
            _HEADER,
            _native_binaries_section(),
            _COMPLIANCE,
            package_sections(dists, _PACKAGES_INTRO),
            full_texts(),
        ]
    )


def generate(out_path: Path | str = DEFAULT_OUT) -> Path:
    """Write the assembled viewer notice document to *out_path* and return it."""
    out = Path(out_path)
    out.write_text(build_document(), encoding="utf-8")
    return out


def main(argv: list[str]) -> int:
    out = Path(argv[1]) if len(argv) > 1 else DEFAULT_OUT
    written = generate(out)
    size = written.stat().st_size
    print(f"[gen-licenses] wrote {written} ({size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
